sudo: required

git:
  quiet: true

jobs:
  include:       
    - os: windows
      language: cpp
      env: BADGE=windows

install:
  - |
    unset CXX CXX_FOR_BUILD CC CC_FOR_BUILD
    choco feature disable -n=showDownloadProgress
    cd ..
    mkdir -p catkin_ws/src
    mv descartes_light catkin_ws/src/
    cd catkin_ws
    choco uninstall mingw
    wget https://raw.githubusercontent.com/johnwason/source_bat/master/source_bat.bash
    source source_bat.bash 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
    choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
    choco install ros-melodic-ros_base -y --execution-timeout=0
    choco install clapack
    choco install openblas
    choco install console_bridge
    source source_bat.bash 'c:\opt\ros\melodic\x64\setup.bat'
    python -m pip install --upgrade pip
    rosdep install --from-paths src --ignore-src -r -y
    /c/opt/vcpkg/vcpkg.exe install jsoncpp:x64-windows
    wstool init src
    wstool merge -t src ./src/descartes_light/dependencies.rosinstall
    wstool update -t src

script:
  - catkin_make_isolated --cmake-args -DCMAKE_BUILD_TYPE=Release -DDESCARTES_ENABLE_TESTING=ON
