/*
 * Software License Agreement (Apache License)
 *
 * Copyright (c) 2021, Southwest Research Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef DESCARTES_LIGHT_DFS_ALL_SOLVER_H
#define DESCARTES_LIGHT_DFS_ALL_SOLVER_H

#include <descartes_light/descartes_macros.h>
DESCARTES_IGNORE_WARNINGS_PUSH
#include <thread>
#include <vector>
DESCARTES_IGNORE_WARNINGS_POP

#include <boost/graph/dijkstra_shortest_paths.hpp>
#include <descartes_light/solvers/bgl/boost_graph_types.h>
#include <descartes_light/core/solver.h>
#include <descartes_light/core/edge_evaluator.h>

namespace descartes_light
{

template <typename FloatType>
class DFSAddAllSolver : public Solver<FloatType>
{
public:
  DFSAddAllSolver(const std::size_t dof, int num_threads = std::thread::hardware_concurrency());

  BuildStatus buildImpl(const std::vector<typename WaypointSampler<FloatType>::ConstPtr>& trajectory,
                        const std::vector<typename EdgeEvaluator<FloatType>::ConstPtr>& edge_eval,
                        const std::vector<typename StateEvaluator<FloatType>::ConstPtr>& state_eval) override;


  SearchResult<FloatType> search() override;

private:
  /**
   * @brief Reconstructs a path through the graph from the source to the target vertex using the predecessor map
   */
  std::vector<VertexDesc<FloatType>> reconstructPath(const VertexDesc<FloatType>& source,
                                                     const VertexDesc<FloatType>& target) const;

  /**
   * @brief Converts a path of vertex descriptors into a path of joint states
   */
  std::vector<typename State<FloatType>::ConstPtr> toStates(const std::vector<VertexDesc<FloatType>>& path) const;


  std::vector<std::vector<VertexDesc<FloatType>>> ladder_rungs_;
  std::vector<typename EdgeEvaluator<FloatType>::ConstPtr> edge_eval{ nullptr };
  std::size_t dof_;
  BGLGraph<FloatType> graph_;
  int num_threads_;
  VertexDesc<FloatType> source_;
  /** @brief Predecessor map generated by the search */
  std::map<VertexDesc<FloatType>, VertexDesc<FloatType>> predecessor_map_;
};

using DFSAddAllSolverF = DFSAddAllSolver<float>;
using DFSAddAllSolverD = DFSAddAllSolver<double>;

}  // namespace descartes_light

#endif  // DESCARTES_LIGHT_DFS_ALL_SOLVER_H
