name: Package-Debian

on:
  push:
    tags:
      - '*'

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  ci:
    name: Package-Debian
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          path: src/descartes_light

      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt install -q -y clang-tidy python3 python3-pip
          sudo pip3 install -q --upgrade pip
          sudo pip3 install -q colcon-common-extensions rosdep vcstool
          sudo rosdep init -q
          rosdep update -q
          vcs import src < src/descartes_light/dependencies.rosinstall
          rosdep install --from-paths src --ignore-src -r -y -q

      - name: Build
        run: |
          colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Release -DDESCARTES_PACKAGE=ON
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Test
        run: |
          colcon test --event-handlers console_direct+ --return-code-on-test-failure
          colcon test-result

      - name: Create artifacts directory
        run: |
          mkdir artifacts

      - name: Package
        working-directory: build/descartes_light
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb ${{ github.workspace }}/artifacts
          cp ./*.tar.xz ${{ github.workspace }}/artifacts

      - name: Upload debians
        uses: actions/upload-artifact@v2
        with:
          name: debian_package
          path: ${{ github.workspace }}/artifacts/*.deb

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: archive_package
          path: ${{ github.workspace }}/artifacts/*.tar.xz
