name: Windows-Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  windows_ci:
    name: Noetic
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        path: src/descartes_light
    - name: Build
      shell: cmd
      run: |
        set ChocolateyInstall=C:\opt\chocolatey
        choco sources add -n=ros-win -s="https://aka.ms/ros/public" --priority=1

        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64

        python -m pip install vcstool -q
        python -m pip install colcon-common-extensions -q
        choco install console_bridge -y --no-progress
        choco install boost -y --no-progress
        choco install eigen -y --no-progress
        refreshenv

        vcs import --input "${{ github.workspace }}/src/descartes_light/dependencies.rosinstall" src/

        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DDESCARTES_ENABLE_TESTING=ON -DCMAKE_PREFIX_PATH=C:\opt\rosdeps
